sources:
  - 01-NonBureau-Normal.glyphspackage.zip
  - 02-NonBureau-Italic.glyphspackage.zip
  - 03-NonBureau-Extended.glyphspackage.zip
  - 04-NonBureau-Extended-Italic.glyphspackage.zip

axisOrder:
  - wght
  - ital
familyName: Non Bureau Collection
