sources:
  - 01-NonBureau-Normal.glyphspackage
  - 02-NonBureau-Italic.glyphspackage
  - 03-NonBureau-Extended.glyphspackage
  - 04-NonBureau-Extended-Italic.glyphspackage
  
axisOrder:
  - wght
  - ital
familyName: Non Bureau Collection
